# 20200527 GOG:From Module 12 - Cloud Security, May 27, 2020
# This lives in the ansible directory within container on the 
# jumpbox-provisioner VM in Azure.
---
  - name: Act03_Playbook
    hosts: webservers
    become: true
    tasks:

# Use APT
    - name: Install docker.io
      apt:
        name: docker.io
        state: present

# Use PIP
    - name: Install python-pip
      apt:
        force_apt_get: yes
        name: python-pip
        state: present

    - name: Install Docker module
      pip:
        name: docker
        state: present

# Use docker container
    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80