# 20200530 GOG: From Module 13 - Elk Stack <ay 30, 2020
# This lives in the ansible directory within container on the 
# jumpbox-provisioner VM in Azure.
---
  - name: Elk Setup
    hosts: elkservers
    become: true
    tasks:

    - name: maxelkserver
      command: 'sysctl -w vm.max_map_count=262144'
# Use APT
    - name: Install docker.io
      apt:
        name: docker.io
        state: present

# Use PIP
    - name: Install python-pip
      apt:
        force_apt_get: yes
        name: python-pip
        state: present

    - name: Install Docker module
      pip:
        name: docker
        state: present

# Use docker container
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk
        state: started
        published_ports:
          - '5601:5601'
          - '9200:9200'
          - '5044:5044'